# .github/workflows/fetch-crdroid.yml
name: fetch crDroid firmware

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'   # প্রতি রবিবার রাতে একবার run করবে (যেমন weekly)

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Download crDroid zip
      run: |
        curl -L "https://master.dl.sourceforge.net/project/crdroid/daisy/6.x/crDroidAndroid-10.0-20210703-daisy-v6.19.zip?viasf=1" -o crDroid-daisy-v6.19.zip

    - name: Commit and push
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "actions@github.com"
        git add crDroid-daisy-v6.19.zip
        git commit -m "Update crDroid daisy v6.19" || echo "No changes"
        git push
